xacro:
  base_mass: 10.0
  base_width: 0.40
  base_length: 0.40
  base_height: 0.10
  wheel_mass: 0.30
  wheel_len: 0.04
  wheel_radius: 0.05
  caster_wheel_mass: 0.10
  caster_wheel_radius: 0.05
  laser_model_z: 0.10
  laser_frame_z: 0.05

drive:
  wheel_layout: diff
  controller_name: robot_base_controller
  controller_type: diff_drive_controller/DiffDriveController

hardware:
  can_id: 42
  motor_freq: 15600
  ticks_per_rotation: 1464
  wheel_radius: 0.05
  speed_scale: 0.50
  max_wheel_angular_velocity_rad_s: 20.0

  # Valid indices: 0..3 for active motors, -1 for unused.
  left_front_motor: 2
  left_rear_motor: 3
  right_front_motor: 0
  right_rear_motor: 1

  invert_left_front_motor: false
  invert_left_rear_motor: false
  invert_right_front_motor: true
  invert_right_rear_motor: true

  invert_left_front_encoder: false
  invert_left_rear_encoder: false
  invert_right_front_encoder: false
  invert_right_rear_encoder: false
