#!/usr/bin/env python3
# Copyright (c) 2026 studica_vmxpi_ros2 contributors
# SPDX-License-Identifier: Apache-2.0
"""Generate terminal-scoped Cyclone DDS profiles for simulation or one robot peer."""

from __future__ import annotations

import argparse
import ipaddress
import os
from pathlib import Path
import re
import shlex
import subprocess
import sys


PACKAGE_NAME = "studica_vmxpi_ros2"
MAX_PARTICIPANT_INDEX = 50
PROFILE_NAME_PATTERN = re.compile(r"^[a-z0-9][a-z0-9_-]*$")
INTERFACE_PATTERN = re.compile(r"^[A-Za-z0-9_.:-]+$")


def _config_directory() -> Path:
    """Find the network templates in a source tree or installed package."""
    script_path = Path(__file__).resolve()
    candidates = (
        script_path.parent.parent / "bringup" / "config" / "network",
        script_path.parent.parent.parent / "share" / PACKAGE_NAME / "config" / "network",
    )
    for candidate in candidates:
        if candidate.joinpath("cyclonedds_sim.xml").is_file():
            return candidate
    searched = "\n  - ".join(str(path) for path in candidates)
    raise RuntimeError(f"Cyclone DDS templates were not found. Searched:\n  - {searched}")


def _ipv4(value: str, label: str) -> ipaddress.IPv4Address:
    """Parse a usable unicast IPv4 address."""
    try:
        address = ipaddress.IPv4Address(value)
    except ipaddress.AddressValueError as error:
        raise ValueError(f"{label} must be an IPv4 address: {value}") from error
    if address.is_unspecified or address.is_multicast or address.is_loopback:
        raise ValueError(f"{label} must be a non-loopback unicast address: {value}")
    return address


def _assigned_ipv4_addresses(interface: str) -> set[ipaddress.IPv4Address]:
    """Return IPv4 addresses assigned to one local interface."""
    result = subprocess.run(
        ["ip", "-o", "-4", "address", "show", "dev", interface],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        detail = result.stderr.strip() or "interface was not found"
        raise ValueError(f"cannot inspect interface {interface}: {detail}")

    addresses: set[ipaddress.IPv4Address] = set()
    for line in result.stdout.splitlines():
        fields = line.split()
        for index, field in enumerate(fields[:-1]):
            if field == "inet":
                addresses.add(ipaddress.IPv4Interface(fields[index + 1]).ip)
    return addresses


def _write_generated(path: Path, content: str, force: bool) -> str:
    """Write one generated file atomically without surprising overwrites."""
    if path.exists():
        if path.read_text(encoding="utf-8") == content:
            return "unchanged"
        if not force:
            raise FileExistsError(f"{path} exists with different content; rerun with --force")

    temporary = path.with_name(f".{path.name}.tmp.{os.getpid()}")
    try:
        temporary.write_text(content, encoding="utf-8")
        temporary.chmod(0o644)
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()
    return "created"


def _environment_content(
    profile_path: Path, domain_id: int, *, gazebo_harmonic: bool = False
) -> str:
    """Return a sourceable shell environment for one generated profile."""
    uri = f"file://{profile_path.resolve()}"
    gazebo_environment = "export GZ_VERSION=harmonic\n" if gazebo_harmonic else ""
    return (
        "# Generated by configure_cyclonedds.py; source this file in one lesson terminal.\n"
        f"{gazebo_environment}"
        f"export ROS_DOMAIN_ID={domain_id}\n"
        "export ROS_LOCALHOST_ONLY=0\n"
        "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp\n"
        f"export CYCLONEDDS_URI={shlex.quote(uri)}\n"
    )


def _parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("sim", "peer"))
    parser.add_argument("--name", help="Profile name, for example pc_wifi or vmxpi_ethernet")
    parser.add_argument("--local-address", help="IPv4 address assigned to this computer")
    parser.add_argument("--peer-address", help="IPv4 address of the other computer")
    parser.add_argument("--interface", help="Selected local interface, for example wlan0 or eth0")
    parser.add_argument("--domain-id", type=int, default=1)
    parser.add_argument("--output-dir", type=Path, default=Path.home() / ".ros")
    parser.add_argument(
        "--skip-interface-check",
        action="store_true",
        help="Generate a peer profile before its interface/address is available",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace a different generated profile",
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_arguments()
    if not 0 <= args.domain_id <= 232:
        print("ERROR: --domain-id must be between 0 and 232", file=sys.stderr)
        return 2

    name = args.name or ("sim" if args.mode == "sim" else "")
    if not PROFILE_NAME_PATTERN.fullmatch(name):
        print("ERROR: --name must use lowercase letters, digits, '_' or '-'", file=sys.stderr)
        return 2

    try:
        config_dir = _config_directory()
        if args.mode == "sim":
            if args.local_address or args.peer_address or args.interface:
                raise ValueError("sim mode does not accept peer addresses or an interface")
            xml_content = config_dir.joinpath("cyclonedds_sim.xml").read_text(encoding="utf-8")
        else:
            if not args.local_address or not args.peer_address or not args.interface:
                raise ValueError(
                    "peer mode requires --local-address, --peer-address, and --interface"
                )
            if not INTERFACE_PATTERN.fullmatch(args.interface):
                raise ValueError(f"invalid interface name: {args.interface}")
            local_address = _ipv4(args.local_address, "--local-address")
            peer_address = _ipv4(args.peer_address, "--peer-address")
            if local_address == peer_address:
                raise ValueError("local and peer addresses must be different")
            if not args.skip_interface_check:
                assigned = _assigned_ipv4_addresses(args.interface)
                if local_address not in assigned:
                    available = ", ".join(str(address) for address in sorted(assigned)) or "none"
                    raise ValueError(
                        f"{local_address} is not assigned to {args.interface} "
                        f"(available: {available})"
                    )
            xml_content = config_dir.joinpath("cyclonedds_peer.xml.in").read_text(
                encoding="utf-8"
            )
            xml_content = xml_content.replace("@LOCAL_ADDRESS@", str(local_address))
            xml_content = xml_content.replace("@PEER_ADDRESS@", str(peer_address))

        output_dir = args.output_dir.expanduser().resolve()
        output_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
        profile_path = output_dir / f"cyclonedds_{name}.xml"
        environment_path = output_dir / f"studica_{name}.env"
        profile_state = _write_generated(profile_path, xml_content, args.force)
        environment_state = _write_generated(
            environment_path,
            _environment_content(
                profile_path,
                args.domain_id,
                gazebo_harmonic=args.mode == "sim",
            ),
            args.force,
        )
    except (FileExistsError, OSError, RuntimeError, ValueError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2

    print(f"{profile_state}: {profile_path}")
    print(f"{environment_state}: {environment_path}")
    print("\nActivate in the current terminal:")
    print(f"  source {shlex.quote(str(environment_path))}")
    print("  ros2 daemon stop")
    print("  ros2 daemon start")

    if args.mode == "peer":
        first_port = 7410 + 250 * args.domain_id
        last_port = 7511 + 250 * args.domain_id
        print(f"\nDDS UDP destination ports for domain {args.domain_id}: {first_port}:{last_port}")
        print("If UFW is active, allow only this peer:")
        print(
            f"  sudo ufw allow in on {shlex.quote(args.interface)} proto udp "
            f"from {args.peer_address} to {args.local_address} port "
            f"{first_port}:{last_port} comment 'Studica ROS 2 DDS domain {args.domain_id}'"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
